auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Jianhua's Page
url: http://www.amoytime.com
feed: /atom.xml
author_info: <a href="http://www.amoytime.com/">Jianjian</a>
