auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Jianhua' blog
url:              http://www.amoytime.com
feed:             /atom.xml
author:
    name:         Jianjian
    twitter:      twitter.com/warmclue
description:      "Jianjian\'s Blog"
author_info:      <a href="http://amoytime.com/about">Jianjian</a>

copyright:
    - Design by <a href="http://amoytime.com/about" title="Jianjian" target="_blank">Jianjian</a> &copy; Copyright 2014
